name: order_status
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.0.3
  auto_route: ^8.0.3
  dio: ^5.4.3+1
  get_it: ^7.7.0
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  uuid: ^4.4.0
  firebase_auth: ^4.19.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true