// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9e4DlgHh5VB3Rd24ZuTy5saMBCRD4V24',
    appId: '1:132174404140:web:28ac229f20add6b6e68f89',
    messagingSenderId: '132174404140',
    projectId: 'order-status-cd24b',
    authDomain: 'order-status-cd24b.firebaseapp.com',
    storageBucket: 'order-status-cd24b.appspot.com',
    measurementId: 'G-WK2SSWE8XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUFeHIxMXR0dkBYA1oUqHnm_Jp49tl1g',
    appId: '1:132174404140:android:12ff565a43e5256be68f89',
    messagingSenderId: '132174404140',
    projectId: 'order-status-cd24b',
    storageBucket: 'order-status-cd24b.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNtzYgDfNIHgXROg5B-yYa0sSemWY23g',
    appId: '1:132174404140:ios:8b2196351be3deb4e68f89',
    messagingSenderId: '132174404140',
    projectId: 'order-status-cd24b',
    storageBucket: 'order-status-cd24b.appspot.com',
    iosBundleId: 'com.example.orderStatus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9e4DlgHh5VB3Rd24ZuTy5saMBCRD4V24',
    appId: '1:132174404140:web:8b60c48f17e704b3e68f89',
    messagingSenderId: '132174404140',
    projectId: 'order-status-cd24b',
    authDomain: 'order-status-cd24b.firebaseapp.com',
    storageBucket: 'order-status-cd24b.appspot.com',
    measurementId: 'G-80FMJJTWFS',
  );
}
